name: 'Testing config import'
type: profile
description: 'Tests install profiles in the config importer.'
# version: VERSION
hidden: true
install:
  - syslog
themes:
  - stark

# Information added by Drupal.org packaging script on 2023-05-03
version: '9.5.9'
project: 'drupal'
datestamp: 1683121616
